// Auto-generated from lazyportfolioetf.com API
// Generated: 2026-05-04T08:55:45.338Z
// Total portfolios: 170

import type { PortfolioDefinition } from '../engine/types';

interface TemplateEntry {
  id: string;
  name: string;
  nameZh: string;
  description: string;
  descriptionZh: string;
  category: string;
  riskLevel: 'low' | 'medium' | 'high';
  holdings: { symbol: string; weight: number }[];
}

const RAW_TEMPLATES: TemplateEntry[] = [
  // ---- Aggressive ----
  {
    id: 'us-stocks',
    name: 'US Stocks',
    nameZh: '',
    description: 'US100',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [],
  },
  {
    id: 'emerging-markets',
    name: 'Emerging Markets Stocks',
    nameZh: '',
    description: 'EM100',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [],
  },
  {
    id: 'rick-ferri-core-four',
    name: 'Core Four',
    nameZh: '',
    description: 'C4',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.48 }, { symbol: 'VEU', weight: 0.24 }, { symbol: 'VNQ', weight: 0.08 }, { symbol: 'BND', weight: 0.2 }],
  },
  {
    id: 'bogleheads-three-funds',
    name: 'Three Funds',
    nameZh: '',
    description: '3F',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.5 }, { symbol: 'VEU', weight: 0.3 }, { symbol: 'BND', weight: 0.2 }],
  },
  {
    id: 'bogleheads-four-funds',
    name: 'Four Funds',
    nameZh: '',
    description: '4F',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.5 }, { symbol: 'VEU', weight: 0.3 }, { symbol: 'TIP', weight: 0.1 }, { symbol: 'BND', weight: 0.1 }],
  },
  {
    id: 'warren-buffett',
    name: 'Warren Buffett Portfolio',
    nameZh: '',
    description: 'WRB',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VV', weight: 0.9 }, { symbol: 'SHY', weight: 0.1 }],
  },
  {
    id: 'world-stocks',
    name: 'Developed World ex-US Stocks',
    nameZh: '',
    description: 'DEV100',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VEA', weight: 1 }],
  },
  {
    id: 'merrill-lynch-edge-select-aggressive',
    name: 'Edge Select Aggressive',
    nameZh: '',
    description: 'MLEA',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VUG', weight: 0.29 }, { symbol: 'VEU', weight: 0.21 }, { symbol: 'VTV', weight: 0.19 }, { symbol: 'EEM', weight: 0.09 }, { symbol: 'IJS', weight: 0.03 }, { symbol: 'IJT', weight: 0.03 }, { symbol: 'IEI', weight: 0.05 }, { symbol: 'LQD', weight: 0.04 }, { symbol: 'MBB', weight: 0.03 }, { symbol: 'BIL', weight: 0.02 }, { symbol: 'BNDX', weight: 0.01 }, { symbol: 'HYG', weight: 0.01 }],
  },
  {
    id: 'robo-advisor-betterment-90',
    name: 'Robo Advisor 90 Value Tilt',
    nameZh: '',
    description: 'RAB90',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.309 }, { symbol: 'VEA', weight: 0.24600000000000002 }, { symbol: 'EEM', weight: 0.14 }, { symbol: 'VTV', weight: 0.08199999999999999 }, { symbol: 'VOE', weight: 0.067 }, { symbol: 'IJS', weight: 0.057 }, { symbol: 'BND', weight: 0.035 }, { symbol: 'BNDX', weight: 0.028999999999999998 }, { symbol: 'EMB', weight: 0.017 }, { symbol: 'TIP', weight: 0.012 }, { symbol: 'BIL', weight: 0.006 }],
  },
  {
    id: 'robo-advisor-betterment-80',
    name: 'Robo Advisor 80  Value Tilt',
    nameZh: '',
    description: 'RAB80',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.27 }, { symbol: 'VEA', weight: 0.221 }, { symbol: 'EEM', weight: 0.128 }, { symbol: 'VTV', weight: 0.07200000000000001 }, { symbol: 'VOE', weight: 0.059000000000000004 }, { symbol: 'IJS', weight: 0.05 }, { symbol: 'BNDX', weight: 0.07200000000000001 }, { symbol: 'BND', weight: 0.068 }, { symbol: 'EMB', weight: 0.036000000000000004 }, { symbol: 'TIP', weight: 0.024 }],
  },
  {
    id: 'european-stocks',
    name: 'European Stocks',
    nameZh: '',
    description: 'EUR',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VGK', weight: 1 }],
  },
  {
    id: 'paul-merriman-ultimate-buy-and-hold-strategy',
    name: 'Ultimate Buy and Hold Strategy',
    nameZh: '',
    description: 'ULT',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'DLS', weight: 0.1 }, { symbol: 'EEM', weight: 0.1 }, { symbol: 'IJR', weight: 0.1 }, { symbol: 'IJS', weight: 0.1 }, { symbol: 'SPY', weight: 0.1 }, { symbol: 'VTV', weight: 0.1 }, { symbol: 'VEA', weight: 0.1 }, { symbol: 'SCZ', weight: 0.1 }, { symbol: 'EFV', weight: 0.1 }, { symbol: 'VNQ', weight: 0.1 }],
  },
  {
    id: 'second-graders-starter',
    name: 'Second Grader\'s Starter',
    nameZh: '',
    description: 'SGS',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.6 }, { symbol: 'VEU', weight: 0.3 }, { symbol: 'BND', weight: 0.1 }],
  },
  {
    id: 'technology',
    name: 'Technology',
    nameZh: '',
    description: 'TEC',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'QQQ', weight: 1 }],
  },
  {
    id: 'robo-advisor-betterment-100',
    name: 'Robo Advisor 100 Value Tilt',
    nameZh: '',
    description: 'RAB100',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.34600000000000003 }, { symbol: 'EFA', weight: 0.273 }, { symbol: 'EEM', weight: 0.15 }, { symbol: 'VTV', weight: 0.092 }, { symbol: 'VOE', weight: 0.075 }, { symbol: 'IJS', weight: 0.064 }],
  },
  {
    id: 'burton-malkiel-late-thirties-to-early-forties',
    name: 'Late Thirties to Early Forties',
    nameZh: '',
    description: 'BM30',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.325 }, { symbol: 'EEM', weight: 0.1625 }, { symbol: 'EFA', weight: 0.1625 }, { symbol: 'VIG', weight: 0.1 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'BIL', weight: 0.05 }, { symbol: 'EMB', weight: 0.05 }, { symbol: 'LQD', weight: 0.05 }],
  },
  {
    id: 'burton-malkiel-mid-fifties',
    name: 'Mid-Fifties',
    nameZh: '',
    description: 'BM50',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.27 }, { symbol: 'EEM', weight: 0.14 }, { symbol: 'EFA', weight: 0.14 }, { symbol: 'VIG', weight: 0.125 }, { symbol: 'VNQ', weight: 0.125 }, { symbol: 'EMB', weight: 0.075 }, { symbol: 'LQD', weight: 0.075 }, { symbol: 'BIL', weight: 0.05 }],
  },
  {
    id: 'burton-malkiel-mid-twnties',
    name: 'Mid-Twenties',
    nameZh: '',
    description: 'BM20',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.35 }, { symbol: 'EEM', weight: 0.175 }, { symbol: 'EFA', weight: 0.175 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'VIG', weight: 0.07 }, { symbol: 'BIL', weight: 0.05 }, { symbol: 'EMB', weight: 0.04 }, { symbol: 'LQD', weight: 0.04 }],
  },
  {
    id: 'aggressive-global-income',
    name: 'Aggressive Global Income',
    nameZh: '',
    description: 'AGLO',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'DWX', weight: 0.3 }, { symbol: 'VYM', weight: 0.3 }, { symbol: 'DES', weight: 0.2 }, { symbol: 'HYG', weight: 0.2 }],
  },
  {
    id: 'stocks-bonds-80-20',
    name: 'Stocks/Bonds 80/20',
    nameZh: '',
    description: 'US80',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.8 }, { symbol: 'BND', weight: 0.2 }],
  },
  {
    id: 'world-developed-80-20',
    name: 'Developed World ex-US 80/20',
    nameZh: '',
    description: 'DEV80',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VEA', weight: 0.8 }, { symbol: 'BNDX', weight: 0.2 }],
  },
  {
    id: 'all-country-world-stocks-portfolio',
    name: 'All Country World Stocks',
    nameZh: '',
    description: 'ALL100',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VT', weight: 1 }],
  },
  {
    id: 'all-country-world-80-20',
    name: 'All Country World 80/20',
    nameZh: '',
    description: 'ALL80',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VT', weight: 0.8 }, { symbol: 'BND', weight: 0.1 }, { symbol: 'BNDX', weight: 0.07 }, { symbol: 'EMB', weight: 0.03 }],
  },
  {
    id: 'us-stocks-esg',
    name: 'US Stocks ESG',
    nameZh: '',
    description: 'US100ESG',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'ESGV', weight: 1 }],
  },
  {
    id: 'us-stocks-momentum',
    name: 'US Stocks Momentum',
    nameZh: '',
    description: 'US100MTM',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'MTUM', weight: 1 }],
  },
  {
    id: 'developed-world-ex-us-stocks-momentum-portfolio',
    name: 'Developed World ex-US Stocks Momentum',
    nameZh: '',
    description: 'DEV100MTM',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'IMTM', weight: 1 }],
  },
  {
    id: 'cape-us-sector-value',
    name: 'Cape US Sector Value',
    nameZh: '',
    description: 'USCAPE',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'CAPE', weight: 1 }],
  },
  {
    id: 'vanguard-lifestrategy-growth-fund',
    name: 'LifeStrategy Growth Fund',
    nameZh: '',
    description: 'LS80',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.48 }, { symbol: 'VEU', weight: 0.32 }, { symbol: 'BND', weight: 0.14 }, { symbol: 'BNDX', weight: 0.06 }],
  },
  {
    id: 'ark-tech-portfolio',
    name: 'Ark Tech Portfolio',
    nameZh: '',
    description: 'ARK',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'ARKG', weight: 0.25 }, { symbol: 'ARKK', weight: 0.25 }, { symbol: 'ARKQ', weight: 0.25 }, { symbol: 'ARKW', weight: 0.25 }],
  },
  {
    id: 'equal-weight-us-portfolio',
    name: 'US Stocks Equal Weight',
    nameZh: '',
    description: 'EUSA',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'RSP', weight: 1 }],
  },
  {
    id: 'ben-stein-perfect-portfolio',
    name: 'Perfect Portfolio',
    nameZh: '',
    description: 'BSP',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'SPY', weight: 0.2 }, { symbol: 'VTI', weight: 0.2 }, { symbol: 'VEA', weight: 0.2 }, { symbol: 'EEM', weight: 0.12 }, { symbol: 'XLE', weight: 0.04 }, { symbol: 'VNQ', weight: 0.04 }, { symbol: 'BIL', weight: 0.2 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-100',
    name: 'Sheltered Sam 100/0',
    nameZh: '',
    description: 'SS100',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTV', weight: 0.25 }, { symbol: 'VV', weight: 0.2 }, { symbol: 'IJS', weight: 0.15 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'EFV', weight: 0.07 }, { symbol: 'EEM', weight: 0.05 }, { symbol: 'IJR', weight: 0.05 }, { symbol: 'VGK', weight: 0.05 }, { symbol: 'VPL', weight: 0.05 }, { symbol: 'GLTR', weight: 0.03 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-90',
    name: 'Sheltered Sam 90/10',
    nameZh: '',
    description: 'SS90',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTV', weight: 0.225 }, { symbol: 'VV', weight: 0.18 }, { symbol: 'IJS', weight: 0.135 }, { symbol: 'VNQ', weight: 0.09 }, { symbol: 'EFV', weight: 0.063 }, { symbol: 'EEM', weight: 0.045 }, { symbol: 'IJR', weight: 0.045 }, { symbol: 'VGK', weight: 0.045 }, { symbol: 'VPL', weight: 0.045 }, { symbol: 'SHY', weight: 0.06 }, { symbol: 'TIP', weight: 0.04 }, { symbol: 'GLTR', weight: 0.027000000000000003 }],
  },
  {
    id: 'ben-stein-long-term-portfolio',
    name: 'Long Term Portfolio',
    nameZh: '',
    description: 'BSLT',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.3 }, { symbol: 'EFA', weight: 0.2 }, { symbol: 'EEM', weight: 0.1 }, { symbol: 'IJS', weight: 0.1 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'BIL', weight: 0.2 }],
  },
  {
    id: 'stocks-bonds-80-20-momentum',
    name: 'Stocks/Bonds 80/20 Momentum',
    nameZh: '',
    description: 'US80MTM',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'MTUM', weight: 0.8 }, { symbol: 'BND', weight: 0.2 }],
  },
  {
    id: 'us-stocks-minimum-volatility',
    name: 'US Stocks Minimum Volatility',
    nameZh: '',
    description: 'US100MV',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'USMV', weight: 1 }],
  },
  {
    id: 'us-stocks-value',
    name: 'US Stocks Value',
    nameZh: '',
    description: 'US100V',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'IUSV', weight: 1 }],
  },
  {
    id: 'dedalo-three',
    name: 'Dedalo Three',
    nameZh: '',
    description: 'DE3',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.7 }, { symbol: 'VT', weight: 0.3 }],
  },
  {
    id: 'dedalo-four',
    name: 'Dedalo Four',
    nameZh: '',
    description: 'DE4',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.55 }, { symbol: 'VT', weight: 0.25 }, { symbol: 'BNDX', weight: 0.2 }],
  },
  {
    id: 'dedalo-eleven',
    name: 'Dedalo Eleven',
    nameZh: '',
    description: 'DE11',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.56 }, { symbol: 'EEM', weight: 0.08 }, { symbol: 'AAXJ', weight: 0.04 }, { symbol: 'EWJ', weight: 0.04 }, { symbol: 'EWL', weight: 0.04 }, { symbol: 'EWU', weight: 0.04 }, { symbol: 'WIP', weight: 0.07 }, { symbol: 'BNDX', weight: 0.07 }, { symbol: 'BND', weight: 0.06 }],
  },
  {
    id: 'us-stocks-quality',
    name: 'US Stocks Quality',
    nameZh: '',
    description: 'US100QUAL',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'QUAL', weight: 1 }],
  },
  {
    id: 'diavola-portfolio-usd',
    name: 'Diavola Portfolio',
    nameZh: '',
    description: 'DIAV',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'VTI', weight: 0.65 }, { symbol: 'QQQ', weight: 0.25 }, { symbol: 'BSV', weight: 0.05 }, { symbol: 'IEI', weight: 0.05 }],
  },
  {
    id: 'warren-buffett-berkshire-hathaway',
    name: 'Berkshire Hathaway',
    nameZh: '',
    description: 'BRKA',
    descriptionZh: '',
    category: 'Aggressive',
    riskLevel: 'high',
    holdings: [{ symbol: 'BRK.A', weight: 1 }],
  },
  // ---- Income ----
  {
    id: 'ray-dalio-all-weather',
    name: 'All Weather Portfolio',
    nameZh: '',
    description: 'DAL',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.3 }, { symbol: 'TLT', weight: 0.4 }, { symbol: 'IEI', weight: 0.15 }, { symbol: 'DBC', weight: 0.075 }, { symbol: 'GLD', weight: 0.075 }],
  },
  {
    id: 'harry-browne-permanent',
    name: 'Permanent Portfolio',
    nameZh: '',
    description: 'BRO',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.25 }, { symbol: 'BIL', weight: 0.25 }, { symbol: 'TLT', weight: 0.25 }, { symbol: 'GLD', weight: 0.25 }],
  },
  {
    id: 'merrill-lynch-edge-select-moderately-conservative',
    name: 'Edge Select Moderately Conservative',
    nameZh: '',
    description: 'MLEMC',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VUG', weight: 0.14 }, { symbol: 'VTV', weight: 0.09 }, { symbol: 'VEU', weight: 0.09 }, { symbol: 'EEM', weight: 0.03 }, { symbol: 'IJS', weight: 0.01 }, { symbol: 'IJT', weight: 0.01 }, { symbol: 'IEI', weight: 0.17 }, { symbol: 'MBB', weight: 0.15 }, { symbol: 'LQD', weight: 0.15 }, { symbol: 'BNDX', weight: 0.09 }, { symbol: 'HYG', weight: 0.05 }, { symbol: 'BIL', weight: 0.02 }],
  },
  {
    id: 'rob-arnott-portfolio',
    name: 'Rob Arnott Portfolio',
    nameZh: '',
    description: 'RAP',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VEU', weight: 0.1 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'VV', weight: 0.1 }, { symbol: 'BNDX', weight: 0.2 }, { symbol: 'LQD', weight: 0.2 }, { symbol: 'TLT', weight: 0.1 }, { symbol: 'TIP', weight: 0.1 }, { symbol: 'DBC', weight: 0.1 }],
  },
  {
    id: 'gyroscopic-investing-desert-portfolio',
    name: 'Desert Portfolio',
    nameZh: '',
    description: 'DES',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.3 }, { symbol: 'IEI', weight: 0.6 }, { symbol: 'GLD', weight: 0.1 }],
  },
  {
    id: 'paul-boyer-permanent-portfolio',
    name: 'Paul Boyer Portfolio',
    nameZh: '',
    description: 'PBPE',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'EEM', weight: 0.125 }, { symbol: 'IJR', weight: 0.125 }, { symbol: 'SHY', weight: 0.25 }, { symbol: 'TLT', weight: 0.25 }, { symbol: 'GLD', weight: 0.25 }],
  },
  {
    id: 'stocks-bonds-40-60-with-bitcoin',
    name: 'Stocks/Bonds 40/60 with Bitcoin',
    nameZh: '',
    description: 'US40BTC',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.39 }, { symbol: 'BND', weight: 0.59 }, { symbol: '^BTC', weight: 0.02 }],
  },
  {
    id: 'ray-dalio-all-weather-with-bitcoin',
    name: 'All Weather Portfolio with Bitcoin',
    nameZh: '',
    description: 'DALBTC',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.3 }, { symbol: 'TLT', weight: 0.4 }, { symbol: 'IEI', weight: 0.15 }, { symbol: 'DBC', weight: 0.065 }, { symbol: 'GLD', weight: 0.065 }, { symbol: '^BTC', weight: 0.02 }],
  },
  {
    id: 'harry-browne-permanent-with-bitcoin',
    name: 'Permanent Portfolio with Bitcoin',
    nameZh: '',
    description: 'BROBTC',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.25 }, { symbol: 'BIL', weight: 0.25 }, { symbol: 'TLT', weight: 0.25 }, { symbol: 'GLD', weight: 0.23 }, { symbol: '^BTC', weight: 0.02 }],
  },
  {
    id: 'ray-dalio-all-weather-2x-leveraged',
    name: 'All Weather Portfolio 2x Leveraged',
    nameZh: '',
    description: 'DAL2X',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'medium',
    holdings: [{ symbol: 'SSO', weight: 0.3 }, { symbol: 'DIG', weight: 0.075 }, { symbol: 'UBT', weight: 0.4 }, { symbol: 'UST', weight: 0.15 }, { symbol: 'UGL', weight: 0.075 }],
  },
  {
    id: 'simplified-permanent-portfolio',
    name: 'Simplified Permanent Portfolio',
    nameZh: '',
    description: 'SPER',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.25 }, { symbol: 'IEF', weight: 0.5 }, { symbol: 'GLD', weight: 0.25 }],
  },
  {
    id: 'simplified-permanent-portfolio-2x-leveraged',
    name: 'Simplified Permanent Portfolio 2x Leveraged',
    nameZh: '',
    description: 'SPER2X',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'SSO', weight: 0.25 }, { symbol: 'UST', weight: 0.5 }, { symbol: 'UGL', weight: 0.25 }],
  },
  {
    id: 'gyroscopic-investing-desert-portfolio-with-bitcoin',
    name: 'Desert Portfolio with Bitcoin',
    nameZh: '',
    description: 'DESBIT',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.3 }, { symbol: 'IEI', weight: 0.6 }, { symbol: 'GLD', weight: 0.08 }, { symbol: '^BTC', weight: 0.02 }],
  },
  {
    id: 'gyroscopic-investing-desert-portfolio-2x-leveraged',
    name: 'Desert Portfolio 2x Leveraged',
    nameZh: '',
    description: 'DES2X',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'SSO', weight: 0.3 }, { symbol: 'UST', weight: 0.6 }, { symbol: 'UGL', weight: 0.1 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-40',
    name: 'Sheltered Sam 40/60',
    nameZh: '',
    description: 'SS40',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTV', weight: 0.1 }, { symbol: 'VV', weight: 0.08 }, { symbol: 'IJS', weight: 0.06 }, { symbol: 'VNQ', weight: 0.04 }, { symbol: 'EFV', weight: 0.027999999999999997 }, { symbol: 'EEM', weight: 0.02 }, { symbol: 'IJR', weight: 0.02 }, { symbol: 'VGK', weight: 0.02 }, { symbol: 'VPL', weight: 0.02 }, { symbol: 'SHY', weight: 0.36 }, { symbol: 'TIP', weight: 0.24 }, { symbol: 'GLTR', weight: 0.012 }],
  },
  {
    id: 'zefiro-portfolio',
    name: 'Zefiro Portfolio',
    nameZh: '',
    description: 'ZEF',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.2 }, { symbol: 'TIP', weight: 0.3 }, { symbol: 'TLT', weight: 0.2 }, { symbol: 'GLD', weight: 0.15 }, { symbol: 'GSG', weight: 0.15 }],
  },
  {
    id: 'pisi-portfolio',
    name: 'PISI Portfolio',
    nameZh: '',
    description: 'PISI',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.3 }, { symbol: 'IEF', weight: 0.5 }, { symbol: 'LQD', weight: 0.1 }, { symbol: 'GLD', weight: 0.1 }],
  },
  {
    id: 'gold-pivot',
    name: 'Gold Pivot Ptf',
    nameZh: '',
    description: 'GLDP',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'QQQ', weight: 0.16 }, { symbol: 'USMV', weight: 0.06 }, { symbol: 'BNDX', weight: 0.31 }, { symbol: 'HYG', weight: 0.13 }, { symbol: 'GLD', weight: 0.34 }],
  },
  {
    id: 'margherita-portfolio-usd',
    name: 'Margherita Portfolio',
    nameZh: '',
    description: 'MARG',
    descriptionZh: '',
    category: 'Income',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.3 }, { symbol: 'IEI', weight: 0.4 }, { symbol: 'BSV', weight: 0.05 }, { symbol: 'CWB', weight: 0.05 }, { symbol: 'TIP', weight: 0.05 }, { symbol: 'LQD', weight: 0.05 }, { symbol: 'GLD', weight: 0.1 }],
  },
  // ---- Commodities ----
  {
    id: 'gold',
    name: 'Gold',
    nameZh: '',
    description: 'GLD',
    descriptionZh: '',
    category: 'Commodities',
    riskLevel: 'low',
    holdings: [],
  },
  {
    id: 'ferdinando-ametrano-new-talmud-usd',
    name: 'New Talmud',
    nameZh: '',
    description: 'P_NEWTALM',
    descriptionZh: '',
    category: 'Commodities',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VT', weight: 0.33 }, { symbol: '^BTC', weight: 0.34 }, { symbol: 'GLD', weight: 0.33 }],
  },
  // ---- Conservative ----
  {
    id: '10-year-treasury',
    name: '10-year Treasury',
    nameZh: '',
    description: '10Y',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [],
  },
  {
    id: 'short-term-treasury',
    name: 'Short Term Treasury',
    nameZh: '',
    description: 'SH',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [],
  },
  {
    id: 'dimensional-retirement-income-fund',
    name: 'Dimensional Retirement Income Fund',
    nameZh: '',
    description: 'DRIF',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'DFEOX', weight: 0.064 }, { symbol: 'DFUSX', weight: 0.064 }, { symbol: 'DFALX', weight: 0.038 }, { symbol: 'DFCEX', weight: 0.019 }, { symbol: 'DFIEX', weight: 0.019 }, { symbol: 'DIPSX', weight: 0.47600000000000003 }, { symbol: 'DFIHX', weight: 0.32 }],
  },
  {
    id: 'merrill-lynch-edge-select-conservative',
    name: 'Edge Select Conservative',
    nameZh: '',
    description: 'MLESC',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTV', weight: 0.08 }, { symbol: 'VUG', weight: 0.05 }, { symbol: 'VEU', weight: 0.05 }, { symbol: 'EEM', weight: 0.01 }, { symbol: 'IJS', weight: 0.01 }, { symbol: 'IJT', weight: 0.01 }, { symbol: 'BIL', weight: 0.24 }, { symbol: 'IEI', weight: 0.17 }, { symbol: 'MBB', weight: 0.12 }, { symbol: 'BNDX', weight: 0.12 }, { symbol: 'LQD', weight: 0.1 }, { symbol: 'HYG', weight: 0.04 }],
  },
  {
    id: 'larry-swedroe-larry-portfolio',
    name: 'Larry Portfolio',
    nameZh: '',
    description: 'LRY',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'IJS', weight: 0.15 }, { symbol: 'DLS', weight: 0.075 }, { symbol: 'EEM', weight: 0.075 }, { symbol: 'IEI', weight: 0.7 }],
  },
  {
    id: 'charles-schwab-convervative-income',
    name: 'Conservative Income',
    nameZh: '',
    description: 'COIN',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VNQ', weight: 0.05 }, { symbol: 'BND', weight: 0.4 }, { symbol: 'BIL', weight: 0.25 }, { symbol: 'TIP', weight: 0.18 }, { symbol: 'HYG', weight: 0.07 }, { symbol: 'BNDX', weight: 0.05 }],
  },
  {
    id: 'robo-advisor-betterment-0',
    name: 'Robo Advisor 0',
    nameZh: '',
    description: 'RAB0',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'SHY', weight: 0.8 }, { symbol: 'BSV', weight: 0.2 }],
  },
  {
    id: 'robo-advisor-betterment-10',
    name: 'Robo Advisor 10  Value Tilt',
    nameZh: '',
    description: 'RAB10',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.032 }, { symbol: 'EFA', weight: 0.027999999999999997 }, { symbol: 'EEM', weight: 0.019 }, { symbol: 'VTV', weight: 0.009000000000000001 }, { symbol: 'IJS', weight: 0.006 }, { symbol: 'VOE', weight: 0.005 }, { symbol: 'SHY', weight: 0.614 }, { symbol: 'BSV', weight: 0.154 }, { symbol: 'BNDX', weight: 0.049 }, { symbol: 'BND', weight: 0.038 }, { symbol: 'EMB', weight: 0.028999999999999998 }, { symbol: 'TIP', weight: 0.017 }],
  },
  {
    id: 'robo-advisor-betterment-20',
    name: 'Robo Advisor 20  Value Tilt',
    nameZh: '',
    description: 'RAB20',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.063 }, { symbol: 'EFA', weight: 0.055999999999999994 }, { symbol: 'EEM', weight: 0.037000000000000005 }, { symbol: 'VTV', weight: 0.017 }, { symbol: 'VOE', weight: 0.013999999999999999 }, { symbol: 'IJS', weight: 0.012 }, { symbol: 'SHY', weight: 0.428 }, { symbol: 'BSV', weight: 0.107 }, { symbol: 'BNDX', weight: 0.098 }, { symbol: 'BND', weight: 0.076 }, { symbol: 'EMB', weight: 0.059000000000000004 }, { symbol: 'TIP', weight: 0.033 }],
  },
  {
    id: 'high-yield-bonds-income',
    name: 'High Yield Bonds Income',
    nameZh: '',
    description: 'HYBO',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'EMB', weight: 0.25 }, { symbol: 'JNK', weight: 0.25 }, { symbol: 'SPLB', weight: 0.25 }, { symbol: 'HYG', weight: 0.25 }],
  },
  {
    id: 'stocks-bonds-20-80',
    name: 'Stocks/Bonds 20/80',
    nameZh: '',
    description: 'US20',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.2 }, { symbol: 'BND', weight: 0.8 }],
  },
  {
    id: 'world-developed-20-80',
    name: 'Developed World ex-US 20/80',
    nameZh: '',
    description: 'DEV20',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VEA', weight: 0.2 }, { symbol: 'BNDX', weight: 0.8 }],
  },
  {
    id: 'total-bond-us',
    name: 'Total Bond US',
    nameZh: '',
    description: 'US0',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'BND', weight: 1 }],
  },
  {
    id: 'total-bond-world-developed',
    name: 'Total Bond Developed World ex-US',
    nameZh: '',
    description: 'DEV0',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'BNDX', weight: 1 }],
  },
  {
    id: 'all-country-world-20-80',
    name: 'All Country World 20/80',
    nameZh: '',
    description: 'ALL20',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VT', weight: 0.2 }, { symbol: 'BND', weight: 0.4 }, { symbol: 'BNDX', weight: 0.28 }, { symbol: 'EMB', weight: 0.12 }],
  },
  {
    id: 'all-country-world-bonds',
    name: 'All Country World Bonds',
    nameZh: '',
    description: 'ALL0',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'BND', weight: 0.5 }, { symbol: 'BNDX', weight: 0.35 }, { symbol: 'EMB', weight: 0.15 }],
  },
  {
    id: 'us-inflation-protection',
    name: 'US Inflation Protection',
    nameZh: '',
    description: 'INFL',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'TIP', weight: 1 }],
  },
  {
    id: 'vanguard-lifestrategy-income-fund',
    name: 'LifeStrategy Income Fund',
    nameZh: '',
    description: 'LS20',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTI', weight: 0.12 }, { symbol: 'VEU', weight: 0.08 }, { symbol: 'BND', weight: 0.56 }, { symbol: 'BNDX', weight: 0.24 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-30',
    name: 'Sheltered Sam 30/70',
    nameZh: '',
    description: 'SS30',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTV', weight: 0.075 }, { symbol: 'VV', weight: 0.06 }, { symbol: 'IJS', weight: 0.045 }, { symbol: 'VNQ', weight: 0.03 }, { symbol: 'EFV', weight: 0.021 }, { symbol: 'EEM', weight: 0.015 }, { symbol: 'IJR', weight: 0.015 }, { symbol: 'VGK', weight: 0.015 }, { symbol: 'VPL', weight: 0.015 }, { symbol: 'SHY', weight: 0.42 }, { symbol: 'TIP', weight: 0.28 }, { symbol: 'GLTR', weight: 0.009000000000000001 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-20',
    name: 'Sheltered Sam 20/80',
    nameZh: '',
    description: 'SS20',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTV', weight: 0.05 }, { symbol: 'VV', weight: 0.04 }, { symbol: 'IJS', weight: 0.03 }, { symbol: 'VNQ', weight: 0.02 }, { symbol: 'EFV', weight: 0.013999999999999999 }, { symbol: 'EEM', weight: 0.01 }, { symbol: 'IJR', weight: 0.01 }, { symbol: 'VGK', weight: 0.01 }, { symbol: 'VPL', weight: 0.01 }, { symbol: 'SHY', weight: 0.48 }, { symbol: 'TIP', weight: 0.32 }, { symbol: 'GLTR', weight: 0.006 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-10',
    name: 'Sheltered Sam 10/90',
    nameZh: '',
    description: 'SS10',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'VTV', weight: 0.025 }, { symbol: 'VV', weight: 0.02 }, { symbol: 'IJS', weight: 0.015 }, { symbol: 'VNQ', weight: 0.01 }, { symbol: 'EFV', weight: 0.006999999999999999 }, { symbol: 'EEM', weight: 0.005 }, { symbol: 'IJR', weight: 0.005 }, { symbol: 'VGK', weight: 0.005 }, { symbol: 'VPL', weight: 0.005 }, { symbol: 'SHY', weight: 0.54 }, { symbol: 'TIP', weight: 0.36 }, { symbol: 'GLTR', weight: 0.003 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-0',
    name: 'Sheltered Sam 0/100',
    nameZh: '',
    description: 'SS0',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'SHY', weight: 0.6 }, { symbol: 'TIP', weight: 0.4 }],
  },
  {
    id: 'larry-swedroe-eliminate-fat-tails-portfolio',
    name: 'Eliminate Fat Tails',
    nameZh: '',
    description: 'EFAT',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'EEM', weight: 0.15 }, { symbol: 'IJR', weight: 0.15 }, { symbol: 'BIL', weight: 0.35 }, { symbol: 'TIP', weight: 0.35 }],
  },
  {
    id: 'stocks-bonds-20-80-momentum',
    name: 'Stocks/Bonds 20/80 Momentum',
    nameZh: '',
    description: 'US20MTM',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'MTUM', weight: 0.2 }, { symbol: 'BND', weight: 0.8 }],
  },
  {
    id: 'us-cash',
    name: 'US Cash',
    nameZh: '',
    description: 'USCASH',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'BIL', weight: 1 }],
  },
  {
    id: 'ulcer-free-strategy',
    name: 'Ulcer Free Strategy',
    nameZh: '',
    description: 'ULFR',
    descriptionZh: '',
    category: 'Conservative',
    riskLevel: 'low',
    holdings: [{ symbol: 'QQQ', weight: 0.11 }, { symbol: 'BNDX', weight: 0.34 }, { symbol: 'IEF', weight: 0.28 }, { symbol: 'CWB', weight: 0.15 }, { symbol: 'GLD', weight: 0.12 }],
  },
  // ---- Growth ----
  {
    id: 'mebane-faber-ivy',
    name: 'Ivy Portfolio',
    nameZh: '',
    description: 'IVY',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.2 }, { symbol: 'VEU', weight: 0.2 }, { symbol: 'VNQ', weight: 0.2 }, { symbol: 'BND', weight: 0.2 }, { symbol: 'GSG', weight: 0.2 }],
  },
  {
    id: 'bill-bernstein-no-brainer',
    name: 'No Brainer Portfolio',
    nameZh: '',
    description: 'NBR',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'IJR', weight: 0.25 }, { symbol: 'VEU', weight: 0.25 }, { symbol: 'VV', weight: 0.25 }, { symbol: 'SHY', weight: 0.25 }],
  },
  {
    id: 'alpha-architect-robust',
    name: 'Robust',
    nameZh: '',
    description: 'AAR',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'MTUM', weight: 0.3 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'DLS', weight: 0.075 }, { symbol: 'IJS', weight: 0.075 }, { symbol: 'VTV', weight: 0.075 }, { symbol: 'EFV', weight: 0.075 }, { symbol: 'IEI', weight: 0.2 }, { symbol: 'GSG', weight: 0.1 }],
  },
  {
    id: 'gibson-five-asset',
    name: 'Five Asset',
    nameZh: '',
    description: 'ROGI',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.2 }, { symbol: 'VEU', weight: 0.2 }, { symbol: 'VNQ', weight: 0.2 }, { symbol: 'BND', weight: 0.14 }, { symbol: 'BNDX', weight: 0.06 }, { symbol: 'DBC', weight: 0.2 }],
  },
  {
    id: 'simple-path-to-wealth',
    name: 'Simple Path to Wealth',
    nameZh: '',
    description: 'SPW',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.75 }, { symbol: 'BND', weight: 0.25 }],
  },
  {
    id: 'pinwheel',
    name: 'Pinwheel',
    nameZh: '',
    description: 'PIN',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'EFA', weight: 0.15 }, { symbol: 'VTI', weight: 0.15 }, { symbol: 'VNQ', weight: 0.15 }, { symbol: 'EEM', weight: 0.1 }, { symbol: 'IJS', weight: 0.1 }, { symbol: 'IEI', weight: 0.15 }, { symbol: 'BIL', weight: 0.1 }, { symbol: 'GLD', weight: 0.1 }],
  },
  {
    id: 'burton-malkiel-late-sixties-and-beyond',
    name: 'Late Sixties and Beyond',
    nameZh: '',
    description: 'BM60',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.2 }, { symbol: 'VIG', weight: 0.16 }, { symbol: 'VNQ', weight: 0.15 }, { symbol: 'EEM', weight: 0.1 }, { symbol: 'EFA', weight: 0.1 }, { symbol: 'BIL', weight: 0.1 }, { symbol: 'EMB', weight: 0.095 }, { symbol: 'LQD', weight: 0.095 }],
  },
  {
    id: 'marc-faber-portfolio',
    name: 'Marc Faber Portfolio',
    nameZh: '',
    description: 'MFB',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VNQ', weight: 0.25 }, { symbol: 'VV', weight: 0.13 }, { symbol: 'VEA', weight: 0.08 }, { symbol: 'EEM', weight: 0.04 }, { symbol: 'BND', weight: 0.25 }, { symbol: 'GLD', weight: 0.25 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-80',
    name: 'Sheltered Sam 80/20',
    nameZh: '',
    description: 'SS80',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTV', weight: 0.2 }, { symbol: 'VV', weight: 0.16 }, { symbol: 'IJS', weight: 0.12 }, { symbol: 'VNQ', weight: 0.08 }, { symbol: 'EFV', weight: 0.055999999999999994 }, { symbol: 'EEM', weight: 0.04 }, { symbol: 'IJR', weight: 0.04 }, { symbol: 'VGK', weight: 0.04 }, { symbol: 'VPL', weight: 0.04 }, { symbol: 'SHY', weight: 0.12 }, { symbol: 'TIP', weight: 0.08 }, { symbol: 'GLTR', weight: 0.024 }],
  },
  {
    id: 'scott-burns-seven-value-portfolio',
    name: 'Seven Value',
    nameZh: '',
    description: '7VAL',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.145 }, { symbol: 'XLE', weight: 0.1425 }, { symbol: 'VTV', weight: 0.1425 }, { symbol: 'VEU', weight: 0.1425 }, { symbol: 'VNQ', weight: 0.1425 }, { symbol: 'TIP', weight: 0.1425 }, { symbol: 'BNDX', weight: 0.1425 }],
  },
  {
    id: 'weird-portfolio',
    name: 'Weird Portfolio',
    nameZh: '',
    description: 'WEI',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'IJS', weight: 0.2 }, { symbol: 'SCZ', weight: 0.2 }, { symbol: 'VNQ', weight: 0.2 }, { symbol: 'TLT', weight: 0.2 }, { symbol: 'GLD', weight: 0.2 }],
  },
  {
    id: 'tony-dong-cockroach-portfolio',
    name: 'Cockroach Portfolio',
    nameZh: '',
    description: 'TDCK',
    descriptionZh: '',
    category: 'Growth',
    riskLevel: 'medium',
    holdings: [{ symbol: 'XLP', weight: 0.2 }, { symbol: 'XLU', weight: 0.2 }, { symbol: 'XLV', weight: 0.2 }, { symbol: 'IEF', weight: 0.2 }, { symbol: 'GLD', weight: 0.2 }],
  },
  // ---- Classic ----
  {
    id: 'scott-burns-couch',
    name: 'Couch Potato',
    nameZh: '',
    description: 'COU',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.5 }, { symbol: 'TIP', weight: 0.5 }],
  },
  {
    id: 'fundadvice-ultimate-buy-hold',
    name: 'Ultimate Buy&Hold',
    nameZh: '',
    description: 'B&H',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'DLS', weight: 0.12 }, { symbol: 'EEM', weight: 0.06 }, { symbol: 'IJR', weight: 0.06 }, { symbol: 'IJS', weight: 0.06 }, { symbol: 'VTV', weight: 0.06 }, { symbol: 'VEA', weight: 0.06 }, { symbol: 'EFV', weight: 0.06 }, { symbol: 'VNQ', weight: 0.06 }, { symbol: 'VV', weight: 0.06 }, { symbol: 'IEI', weight: 0.2 }, { symbol: 'SHY', weight: 0.12 }, { symbol: 'TIP', weight: 0.08 }],
  },
  {
    id: 'stocks-bonds-60-40',
    name: 'Stocks/Bonds 60/40',
    nameZh: '',
    description: 'US60',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.6 }, { symbol: 'BND', weight: 0.4 }],
  },
  {
    id: 'bill-schultheis-coffee-house',
    name: 'Coffeehouse',
    nameZh: '',
    description: 'CFF',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'IJR', weight: 0.1 }, { symbol: 'IJS', weight: 0.1 }, { symbol: 'VTV', weight: 0.1 }, { symbol: 'VEU', weight: 0.1 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'VV', weight: 0.1 }, { symbol: 'BND', weight: 0.4 }],
  },
  {
    id: 'david-swensen-lazy',
    name: 'Lazy Portfolio',
    nameZh: '',
    description: 'LZY',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.3 }, { symbol: 'VNQ', weight: 0.2 }, { symbol: 'VEU', weight: 0.15 }, { symbol: 'EEM', weight: 0.05 }, { symbol: 'IEI', weight: 0.15 }, { symbol: 'TIP', weight: 0.15 }],
  },
  {
    id: 'david-swensen-yale-endowment',
    name: 'Yale Endowment',
    nameZh: '',
    description: 'YAL',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.3 }, { symbol: 'VNQ', weight: 0.2 }, { symbol: 'VEA', weight: 0.15 }, { symbol: 'EEM', weight: 0.05 }, { symbol: 'IEI', weight: 0.15 }, { symbol: 'TIP', weight: 0.15 }],
  },
  {
    id: 'dimensional-2030-target-date-retirement-income-fund',
    name: 'Dimensional 2030 Retirement Income',
    nameZh: '',
    description: '2030',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.175 }, { symbol: 'VV', weight: 0.175 }, { symbol: 'VEA', weight: 0.105 }, { symbol: 'EEM', weight: 0.052000000000000005 }, { symbol: 'VEU', weight: 0.052000000000000005 }, { symbol: 'TIP', weight: 0.319 }, { symbol: 'BSV', weight: 0.061 }, { symbol: 'BNDX', weight: 0.061 }],
  },
  {
    id: 'frank-armstrong-ideal-index',
    name: 'Ideal Index',
    nameZh: '',
    description: 'IDEAL',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VEU', weight: 0.31 }, { symbol: 'IJS', weight: 0.0925 }, { symbol: 'VTV', weight: 0.0925 }, { symbol: 'VNQ', weight: 0.08 }, { symbol: 'IJT', weight: 0.0625 }, { symbol: 'VV', weight: 0.0625 }, { symbol: 'SHY', weight: 0.3 }],
  },
  {
    id: 'merrill-lynch-edge-select-moderate',
    name: 'Edge Select Moderate',
    nameZh: '',
    description: 'MLESM',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VUG', weight: 0.19 }, { symbol: 'VEU', weight: 0.13 }, { symbol: 'VTV', weight: 0.12 }, { symbol: 'EEM', weight: 0.05 }, { symbol: 'IJS', weight: 0.02 }, { symbol: 'IJT', weight: 0.02 }, { symbol: 'IEI', weight: 0.14 }, { symbol: 'LQD', weight: 0.14 }, { symbol: 'MBB', weight: 0.11 }, { symbol: 'HYG', weight: 0.04 }, { symbol: 'BIL', weight: 0.02 }, { symbol: 'BNDX', weight: 0.02 }],
  },
  {
    id: 'merrill-lynch-edge-select-moderately-aggressive',
    name: 'Edge Select Moderately Aggressive',
    nameZh: '',
    description: 'MLEMA',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VUG', weight: 0.25 }, { symbol: 'VEU', weight: 0.17 }, { symbol: 'VTV', weight: 0.16 }, { symbol: 'EEM', weight: 0.07 }, { symbol: 'IJS', weight: 0.02 }, { symbol: 'IJT', weight: 0.02 }, { symbol: 'IEI', weight: 0.09 }, { symbol: 'LQD', weight: 0.09 }, { symbol: 'MBB', weight: 0.07 }, { symbol: 'HYG', weight: 0.03 }, { symbol: 'BIL', weight: 0.02 }, { symbol: 'BNDX', weight: 0.01 }],
  },
  {
    id: 'bill-bernstein-cowards-portfolio',
    name: 'Coward\'s Portfolio',
    nameZh: '',
    description: 'COW',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VV', weight: 0.15 }, { symbol: 'IJS', weight: 0.1 }, { symbol: 'VTV', weight: 0.1 }, { symbol: 'EEM', weight: 0.05 }, { symbol: 'IJR', weight: 0.05 }, { symbol: 'VGK', weight: 0.05 }, { symbol: 'VPL', weight: 0.05 }, { symbol: 'VNQ', weight: 0.05 }, { symbol: 'SHY', weight: 0.4 }],
  },
  {
    id: 'scott-burns-margaritaville',
    name: 'Margaritaville',
    nameZh: '',
    description: 'MAR',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.34 }, { symbol: 'VEU', weight: 0.33 }, { symbol: 'TIP', weight: 0.33 }],
  },
  {
    id: 'roger-gibson-talmud-portfolio',
    name: 'Talmud Portfolio',
    nameZh: '',
    description: 'TAL',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.33340000000000003 }, { symbol: 'VNQ', weight: 0.3333 }, { symbol: 'BND', weight: 0.3333 }],
  },
  {
    id: 'bob-clyatt-sandwich-portfolio',
    name: 'Sandwich Portfolio',
    nameZh: '',
    description: 'SAN',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VV', weight: 0.2 }, { symbol: 'SCZ', weight: 0.1 }, { symbol: 'IJR', weight: 0.08 }, { symbol: 'EEM', weight: 0.06 }, { symbol: 'VEU', weight: 0.06 }, { symbol: 'VNQ', weight: 0.05 }, { symbol: 'IEI', weight: 0.41 }, { symbol: 'BIL', weight: 0.04 }],
  },
  {
    id: 'craig-israelsen-7twelve-portfolio',
    name: '7Twelve Portfolio',
    nameZh: '',
    description: '7TW',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VNQ', weight: 0.0834 }, { symbol: 'VV', weight: 0.0834 }, { symbol: 'EEM', weight: 0.0833 }, { symbol: 'EFA', weight: 0.0833 }, { symbol: 'IJR', weight: 0.0833 }, { symbol: 'VO', weight: 0.0833 }, { symbol: 'IEI', weight: 0.25 }, { symbol: 'BIL', weight: 0.0834 }, { symbol: 'GSG', weight: 0.1666 }],
  },
  {
    id: 'tim-maurer-simple-money-portfolio',
    name: 'Simple Money Portfolio',
    nameZh: '',
    description: 'SIM',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'SCZ', weight: 0.15 }, { symbol: 'EFV', weight: 0.15 }, { symbol: 'IJR', weight: 0.075 }, { symbol: 'IJS', weight: 0.075 }, { symbol: 'VTV', weight: 0.075 }, { symbol: 'VV', weight: 0.075 }, { symbol: 'IEI', weight: 0.4 }],
  },
  {
    id: 'ted-aronson-family-taxable',
    name: 'Family Taxable Portfolio',
    nameZh: '',
    description: 'TAX',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VPL', weight: 0.15 }, { symbol: 'VV', weight: 0.15 }, { symbol: 'EEM', weight: 0.1 }, { symbol: 'IJR', weight: 0.1 }, { symbol: 'IJS', weight: 0.05 }, { symbol: 'IJT', weight: 0.05 }, { symbol: 'VTI', weight: 0.05 }, { symbol: 'VGK', weight: 0.05 }, { symbol: 'TIP', weight: 0.15 }, { symbol: 'TLT', weight: 0.1 }, { symbol: 'HYG', weight: 0.05 }],
  },
  {
    id: 'larry-swedroe-big-rocks-portfolio',
    name: 'Big Rocks Portfolio',
    nameZh: '',
    description: 'BIG',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'IJR', weight: 0.09 }, { symbol: 'IJS', weight: 0.09 }, { symbol: 'VTV', weight: 0.09 }, { symbol: 'VV', weight: 0.09 }, { symbol: 'EFV', weight: 0.06 }, { symbol: 'VNQ', weight: 0.06 }, { symbol: 'DLS', weight: 0.03 }, { symbol: 'EEM', weight: 0.03 }, { symbol: 'VEU', weight: 0.03 }, { symbol: 'SCZ', weight: 0.03 }, { symbol: 'SHY', weight: 0.4 }],
  },
  {
    id: 'andrew-tobias-portfolio',
    name: 'Andrew Tobias Portfolio',
    nameZh: '',
    description: 'ATOB',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.33340000000000003 }, { symbol: 'EFA', weight: 0.3333 }, { symbol: 'SHY', weight: 0.3333 }],
  },
  {
    id: 'alexander-green-gone-fishin-portfolio',
    name: 'Gone Fishin\' Portfolio',
    nameZh: '',
    description: 'FISH',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'IJR', weight: 0.15 }, { symbol: 'VTI', weight: 0.15 }, { symbol: 'EEM', weight: 0.1 }, { symbol: 'VGK', weight: 0.1 }, { symbol: 'VPL', weight: 0.1 }, { symbol: 'VNQ', weight: 0.05 }, { symbol: 'TIP', weight: 0.1 }, { symbol: 'BND', weight: 0.1 }, { symbol: 'HYG', weight: 0.1 }, { symbol: 'GLTR', weight: 0.05 }],
  },
  {
    id: 'dynamic-60-40-income',
    name: 'Dynamic 60/40 Income',
    nameZh: '',
    description: 'DYN60',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'PFF', weight: 0.2 }, { symbol: 'VTI', weight: 0.2 }, { symbol: 'VNQ', weight: 0.2 }, { symbol: 'SHY', weight: 0.2 }, { symbol: 'HYG', weight: 0.2 }],
  },
  {
    id: 'world-developed-60-40',
    name: 'Developed World ex-US 60/40',
    nameZh: '',
    description: 'DEV60',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VEA', weight: 0.6 }, { symbol: 'BNDX', weight: 0.4 }],
  },
  {
    id: 'all-country-world-60-40',
    name: 'All Country World 60/40',
    nameZh: '',
    description: 'ALL60',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VT', weight: 0.6 }, { symbol: 'BND', weight: 0.2 }, { symbol: 'BNDX', weight: 0.14 }, { symbol: 'EMB', weight: 0.06 }],
  },
  {
    id: 'stocks-bonds-60-40-with-bitcoin',
    name: 'Stocks/Bonds 60/40 with Bitcoin',
    nameZh: '',
    description: 'US60BTC',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.59 }, { symbol: 'BND', weight: 0.39 }, { symbol: '^BTC', weight: 0.02 }],
  },
  {
    id: 'stocks-bonds-60-40-esg',
    name: 'Stocks/Bonds 60/40 ESG',
    nameZh: '',
    description: 'US60ESG',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'ESGV', weight: 0.6 }, { symbol: 'NUBD', weight: 0.4 }],
  },
  {
    id: 'stocks-bonds-60-40-momentum',
    name: 'Stocks/Bonds 60/40 Momentum',
    nameZh: '',
    description: 'US60MTM',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'MTUM', weight: 0.6 }, { symbol: 'BND', weight: 0.4 }],
  },
  {
    id: 'world-developed-60-40-momentum',
    name: 'Developed World ex-US 60/40 Momentum',
    nameZh: '',
    description: 'DEV60MTM',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'IMTM', weight: 0.6 }, { symbol: 'BNDX', weight: 0.4 }],
  },
  {
    id: 'stocks-bonds-60-40-2x-leveraged',
    name: 'Stocks/Bonds 60/40 2x Leveraged',
    nameZh: '',
    description: 'US60x2',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'SSO', weight: 0.6 }, { symbol: 'UST', weight: 0.4 }],
  },
  {
    id: 'roger-gibson-talmud-portfolio-2x-leveraged',
    name: 'Talmud Portfolio 2x Leveraged',
    nameZh: '',
    description: 'TAL2x',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'SSO', weight: 0.33340000000000003 }, { symbol: 'URE', weight: 0.3333 }, { symbol: 'UST', weight: 0.3333 }],
  },
  {
    id: 'jane-bryant-quinn-portfolio',
    name: 'Jane Bryant Quinn Portfolio',
    nameZh: '',
    description: 'JBQ',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.4 }, { symbol: 'VEA', weight: 0.2 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'BND', weight: 0.2 }, { symbol: 'TIP', weight: 0.1 }],
  },
  {
    id: 'vanguard-lifestrategy-moderate-growth',
    name: 'LifeStrategy Moderate Growth',
    nameZh: '',
    description: 'LS60',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.36 }, { symbol: 'VEU', weight: 0.24 }, { symbol: 'BND', weight: 0.28 }, { symbol: 'BNDX', weight: 0.12 }],
  },
  {
    id: 'marvin-appel-one-decision',
    name: 'One-Decision Portfolio',
    nameZh: '',
    description: '1DEC',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'SPY', weight: 0.2 }, { symbol: 'VNQ', weight: 0.2 }, { symbol: 'IJS', weight: 0.1 }, { symbol: 'BIL', weight: 0.3 }, { symbol: 'LQD', weight: 0.2 }],
  },
  {
    id: 'john-wasik-nano',
    name: 'Nano Portfolio',
    nameZh: '',
    description: 'NANO',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'EFA', weight: 0.2 }, { symbol: 'VTI', weight: 0.2 }, { symbol: 'VNQ', weight: 0.2 }, { symbol: 'TIP', weight: 0.2 }, { symbol: 'BND', weight: 0.2 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-70',
    name: 'Sheltered Sam 70/30',
    nameZh: '',
    description: 'SS70',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTV', weight: 0.175 }, { symbol: 'VV', weight: 0.14 }, { symbol: 'IJS', weight: 0.105 }, { symbol: 'VNQ', weight: 0.07 }, { symbol: 'EFV', weight: 0.049 }, { symbol: 'EEM', weight: 0.035 }, { symbol: 'IJR', weight: 0.035 }, { symbol: 'VGK', weight: 0.035 }, { symbol: 'VPL', weight: 0.035 }, { symbol: 'SHY', weight: 0.18 }, { symbol: 'TIP', weight: 0.12 }, { symbol: 'GLTR', weight: 0.021 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-60',
    name: 'Sheltered Sam 60/40',
    nameZh: '',
    description: 'SS60',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTV', weight: 0.15 }, { symbol: 'VV', weight: 0.12 }, { symbol: 'IJS', weight: 0.09 }, { symbol: 'VNQ', weight: 0.06 }, { symbol: 'EFV', weight: 0.042 }, { symbol: 'EEM', weight: 0.03 }, { symbol: 'IJR', weight: 0.03 }, { symbol: 'VGK', weight: 0.03 }, { symbol: 'VPL', weight: 0.03 }, { symbol: 'SHY', weight: 0.24 }, { symbol: 'TIP', weight: 0.16 }, { symbol: 'GLTR', weight: 0.018000000000000002 }],
  },
  {
    id: 'scott-burns-six-ways-from-sunday',
    name: 'Six Ways from Sunday',
    nameZh: '',
    description: '6WAY',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.16699999999999998 }, { symbol: 'XLE', weight: 0.1666 }, { symbol: 'VEU', weight: 0.1666 }, { symbol: 'VNQ', weight: 0.1666 }, { symbol: 'TIP', weight: 0.1666 }, { symbol: 'BNDX', weight: 0.1666 }],
  },
  {
    id: 'scott-burns-four-square-portfolio',
    name: 'Four Square',
    nameZh: '',
    description: '4SQ',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.25 }, { symbol: 'VEU', weight: 0.25 }, { symbol: 'TIP', weight: 0.25 }, { symbol: 'BNDX', weight: 0.25 }],
  },
  {
    id: 'scott-burns-five-fold-portfolio',
    name: 'Five Fold',
    nameZh: '',
    description: '5FLD',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.2 }, { symbol: 'VEU', weight: 0.2 }, { symbol: 'VNQ', weight: 0.2 }, { symbol: 'TIP', weight: 0.2 }, { symbol: 'BNDX', weight: 0.2 }],
  },
  {
    id: 'time-inc-simple-and-cheap-portfolio',
    name: 'Simple and Cheap',
    nameZh: '',
    description: 'TiSC',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.3 }, { symbol: 'VEU', weight: 0.2 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'BND', weight: 0.3 }, { symbol: 'BNDX', weight: 0.1 }],
  },
  {
    id: 'time-inc-tilt-toward-value-portfolio',
    name: 'Tilt Toward Value',
    nameZh: '',
    description: 'TTV',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.25 }, { symbol: 'VEU', weight: 0.15 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'IJS', weight: 0.05 }, { symbol: 'VTV', weight: 0.05 }, { symbol: 'BND', weight: 0.3 }, { symbol: 'BNDX', weight: 0.1 }],
  },
  {
    id: 'gretchen-tai-portfolio',
    name: 'Gretchen Tai Portfolio',
    nameZh: '',
    description: 'GTAI',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.26 }, { symbol: 'VEA', weight: 0.26 }, { symbol: 'EEM', weight: 0.1 }, { symbol: 'REET', weight: 0.05 }, { symbol: 'IJR', weight: 0.03 }, { symbol: 'BND', weight: 0.1 }, { symbol: 'TIP', weight: 0.08 }, { symbol: 'HYG', weight: 0.08 }, { symbol: 'TLT', weight: 0.04 }],
  },
  {
    id: 'pepperoni-portfolio-usd',
    name: 'Pepperoni Portfolio',
    nameZh: '',
    description: 'PEPP',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.5 }, { symbol: 'QQQ', weight: 0.1 }, { symbol: 'IEI', weight: 0.3 }, { symbol: 'BSV', weight: 0.05 }, { symbol: 'CWB', weight: 0.05 }],
  },
  {
    id: 'capricciosa-portfolio-usd',
    name: 'Capricciosa Portfolio',
    nameZh: '',
    description: 'CAPR',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.5 }, { symbol: 'IEI', weight: 0.3 }, { symbol: 'BSV', weight: 0.05 }, { symbol: 'CWB', weight: 0.05 }, { symbol: 'LQD', weight: 0.05 }, { symbol: 'GLD', weight: 0.05 }],
  },
  {
    id: 'jp-morgan-balanced-portfolio-usd',
    name: 'JP Morgan Balanced Portfolio',
    nameZh: '',
    description: 'JPM_BAL',
    descriptionZh: '',
    category: 'Classic',
    riskLevel: 'medium',
    holdings: [{ symbol: 'SPY', weight: 0.25 }, { symbol: 'EFA', weight: 0.15 }, { symbol: 'IJR', weight: 0.1 }, { symbol: 'EEM', weight: 0.05 }, { symbol: 'VNQ', weight: 0.05 }, { symbol: 'BND', weight: 0.25 }, { symbol: 'BIL', weight: 0.05 }, { symbol: 'HYG', weight: 0.05 }, { symbol: 'DBC', weight: 0.05 }],
  },
  // ---- Balanced ----
  {
    id: 'stocks-bonds-40-60',
    name: 'Stocks/Bonds 40/60',
    nameZh: '',
    description: 'US40',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.4 }, { symbol: 'BND', weight: 0.6 }],
  },
  {
    id: 'ishares-lifepath-fund',
    name: 'Lifepath Fund',
    nameZh: '',
    description: 'ISHRE',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VV', weight: 0.22089999999999999 }, { symbol: 'VEU', weight: 0.1367 }, { symbol: 'IJR', weight: 0.0415 }, { symbol: 'VNQ', weight: 0.0051 }, { symbol: 'BND', weight: 0.5082 }, { symbol: 'TIP', weight: 0.0876 }],
  },
  {
    id: 'robo-advisor-betterment-50',
    name: 'Robo Advisor 50  Value Tilt',
    nameZh: '',
    description: 'RAB50',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.162 }, { symbol: 'EFA', weight: 0.13699999999999998 }, { symbol: 'EEM', weight: 0.09 }, { symbol: 'VTV', weight: 0.044000000000000004 }, { symbol: 'VOE', weight: 0.036000000000000004 }, { symbol: 'IJS', weight: 0.03 }, { symbol: 'BNDX', weight: 0.184 }, { symbol: 'BND', weight: 0.147 }, { symbol: 'EMB', weight: 0.107 }, { symbol: 'TIP', weight: 0.063 }],
  },
  {
    id: 'dynamic-40-60-income',
    name: 'Dynamic 40/60 Income',
    nameZh: '',
    description: 'DYN40',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'PFF', weight: 0.2 }, { symbol: 'VTI', weight: 0.2 }, { symbol: 'EMB', weight: 0.2 }, { symbol: 'SHY', weight: 0.2 }, { symbol: 'HYG', weight: 0.2 }],
  },
  {
    id: 'world-developed-40-60',
    name: 'Developed World ex-US 40/60',
    nameZh: '',
    description: 'DEV40',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VEA', weight: 0.4 }, { symbol: 'BNDX', weight: 0.6 }],
  },
  {
    id: 'all-country-world-40-60',
    name: 'All Country World 40/60',
    nameZh: '',
    description: 'ALL40',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VT', weight: 0.4 }, { symbol: 'BND', weight: 0.3 }, { symbol: 'BNDX', weight: 0.21 }, { symbol: 'EMB', weight: 0.09 }],
  },
  {
    id: 'stocks-bonds-40-60-esg',
    name: 'Stocks/Bonds 40/60 ESG',
    nameZh: '',
    description: 'US40ESG',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'ESGV', weight: 0.4 }, { symbol: 'NUBD', weight: 0.6 }],
  },
  {
    id: 'stocks-bonds-40-60-momentum',
    name: 'Stocks/Bonds 40/60 Momentum',
    nameZh: '',
    description: 'US40MTM',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'MTUM', weight: 0.4 }, { symbol: 'BND', weight: 0.6 }],
  },
  {
    id: 'world-developed-40-60-momentum',
    name: 'Developed World ex-US 40/60 Momentum',
    nameZh: '',
    description: 'DEV40MTM',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'IMTM', weight: 0.4 }, { symbol: 'BNDX', weight: 0.6 }],
  },
  {
    id: 'stocks-bonds-40-60-2x-leveraged',
    name: 'Stocks/Bonds 40/60 2x Leveraged',
    nameZh: '',
    description: 'US40x2',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'SSO', weight: 0.4 }, { symbol: 'UST', weight: 0.6 }],
  },
  {
    id: 'vanguard-lifestrategy-conservative-growth',
    name: 'LifeStrategy Conservative Growth',
    nameZh: '',
    description: 'LS40',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.24 }, { symbol: 'VEU', weight: 0.16 }, { symbol: 'BND', weight: 0.42 }, { symbol: 'BNDX', weight: 0.18 }],
  },
  {
    id: 'credit-suisse-global-market',
    name: 'Global Market Portfolio',
    nameZh: '',
    description: 'GMP',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'SPY', weight: 0.2 }, { symbol: 'VEU', weight: 0.15 }, { symbol: 'EEM', weight: 0.05 }, { symbol: 'VNQ', weight: 0.05 }, { symbol: 'LQD', weight: 0.22 }, { symbol: 'BNDX', weight: 0.16 }, { symbol: 'TLT', weight: 0.15 }, { symbol: 'TIP', weight: 0.02 }],
  },
  {
    id: 'bill-bernstein-sheltered-sam-50',
    name: 'Sheltered Sam 50/50',
    nameZh: '',
    description: 'SS50',
    descriptionZh: '',
    category: 'Balanced',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTV', weight: 0.125 }, { symbol: 'VV', weight: 0.1 }, { symbol: 'IJS', weight: 0.075 }, { symbol: 'VNQ', weight: 0.05 }, { symbol: 'EFV', weight: 0.035 }, { symbol: 'EEM', weight: 0.025 }, { symbol: 'IJR', weight: 0.025 }, { symbol: 'VGK', weight: 0.025 }, { symbol: 'VPL', weight: 0.025 }, { symbol: 'SHY', weight: 0.3 }, { symbol: 'TIP', weight: 0.2 }, { symbol: 'GLTR', weight: 0.015 }],
  },
  // ---- Risk Parity ----
  {
    id: 'golden-butterfly',
    name: 'Golden Butterfly',
    nameZh: '',
    description: 'BTF',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'IJS', weight: 0.2 }, { symbol: 'VTI', weight: 0.2 }, { symbol: 'SHY', weight: 0.2 }, { symbol: 'TLT', weight: 0.2 }, { symbol: 'GLD', weight: 0.2 }],
  },
  {
    id: 'gaa-global-asset-allocation',
    name: 'GAA Global Asset Allocation',
    nameZh: '',
    description: 'GAA',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VV', weight: 0.18 }, { symbol: 'VEA', weight: 0.135 }, { symbol: 'EEM', weight: 0.045 }, { symbol: 'VNQ', weight: 0.045 }, { symbol: 'LQD', weight: 0.198 }, { symbol: 'BNDX', weight: 0.14400000000000002 }, { symbol: 'TLT', weight: 0.135 }, { symbol: 'TIP', weight: 0.018000000000000002 }, { symbol: 'GLD', weight: 0.05 }, { symbol: 'GSG', weight: 0.05 }],
  },
  {
    id: 'golden-butterfly-with-bitcoin',
    name: 'Golden Butterfly with Bitcoin',
    nameZh: '',
    description: 'BTFBTC',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'IJS', weight: 0.2 }, { symbol: 'VTI', weight: 0.2 }, { symbol: 'SHY', weight: 0.2 }, { symbol: 'TLT', weight: 0.2 }, { symbol: 'GLD', weight: 0.18 }, { symbol: '^BTC', weight: 0.02 }],
  },
  {
    id: 'golden-butterfly-2x-leveraged',
    name: 'Golden Butterfly 2x Leveraged',
    nameZh: '',
    description: 'BTF2x',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'SAA', weight: 0.2 }, { symbol: 'SSO', weight: 0.2 }, { symbol: 'UST', weight: 0.4 }, { symbol: 'UGL', weight: 0.2 }],
  },
  {
    id: 'aim-bold-strategy',
    name: 'Aim Bold Strategy',
    nameZh: '',
    description: 'AIMB',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'QQQ', weight: 0.15 }, { symbol: 'VTI', weight: 0.15 }, { symbol: 'VGK', weight: 0.1 }, { symbol: 'AAXJ', weight: 0.05 }, { symbol: 'BNDX', weight: 0.2 }, { symbol: 'HYG', weight: 0.2 }, { symbol: 'GLD', weight: 0.15 }],
  },
  {
    id: 'shield-strategy',
    name: 'Shield Strategy',
    nameZh: '',
    description: 'SHST',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'SPY', weight: 0.21 }, { symbol: 'QQQ', weight: 0.16 }, { symbol: 'USMV', weight: 0.05 }, { symbol: 'LQD', weight: 0.22 }, { symbol: 'IEI', weight: 0.16 }, { symbol: 'GLD', weight: 0.2 }],
  },
  {
    id: 'in-saecula-saeculorum',
    name: 'In Saecula Saeculorum',
    nameZh: '',
    description: 'SS',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.45 }, { symbol: 'IEF', weight: 0.2 }, { symbol: 'LQD', weight: 0.15 }, { symbol: 'SHY', weight: 0.1 }, { symbol: 'GLD', weight: 0.1 }],
  },
  {
    id: 'aim-comfortable-trip',
    name: 'Aim comfortable trip',
    nameZh: '',
    description: 'ACTR',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'EFV', weight: 0.13 }, { symbol: 'QQQ', weight: 0.11 }, { symbol: 'IJS', weight: 0.1 }, { symbol: 'USMV', weight: 0.06 }, { symbol: 'BNDX', weight: 0.28 }, { symbol: 'BSV', weight: 0.17 }, { symbol: 'GLD', weight: 0.15 }],
  },
  {
    id: 'odd-stats-strategy',
    name: 'Odd-Stats Strategy',
    nameZh: '',
    description: 'ODDS',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'QQQ', weight: 0.22 }, { symbol: 'USMV', weight: 0.15 }, { symbol: 'VNQ', weight: 0.1 }, { symbol: 'BNDX', weight: 0.23 }, { symbol: 'IEF', weight: 0.2 }, { symbol: 'GLD', weight: 0.1 }],
  },
  {
    id: 'four-seasons-portfolio-usd',
    name: 'Four Seasons Portfolio',
    nameZh: '',
    description: 'FOUR',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'VTI', weight: 0.4 }, { symbol: 'IEI', weight: 0.3 }, { symbol: 'BSV', weight: 0.05 }, { symbol: 'CWB', weight: 0.05 }, { symbol: 'TIP', weight: 0.05 }, { symbol: 'LQD', weight: 0.05 }, { symbol: 'GLD', weight: 0.1 }],
  },
  {
    id: 'frank-vasquez-golden-ratio-portfolio',
    name: 'Golden Ratio Portfolio',
    nameZh: '',
    description: 'GRAT',
    descriptionZh: '',
    category: 'Risk Parity',
    riskLevel: 'medium',
    holdings: [{ symbol: 'IJS', weight: 0.21 }, { symbol: 'VUG', weight: 0.21 }, { symbol: 'TLT', weight: 0.26 }, { symbol: 'BIL', weight: 0.06 }, { symbol: 'GLD', weight: 0.16 }, { symbol: 'DBMF', weight: 0.1 }],
  },
];

export function getPortfolioTemplates(
  getAssetBySymbol: (symbol: string) => { symbol: string; name: string; nameZh?: string; assetClass: string; region: string; currency: string; provider: string; expenseRatio: number; inceptionDate: string } | null,
): PortfolioDefinition[] {
  return RAW_TEMPLATES.map((t) => ({
    id: t.id,
    name: t.name,
    description: t.description,
    holdings: t.holdings
      .map((h) => {
        const asset = getAssetBySymbol(h.symbol);
        if (!asset) return null;
        return {
          asset: {
            symbol: asset.symbol,
            name: asset.name,
            nameZh: asset.nameZh,
            assetClass: asset.assetClass as PortfolioDefinition['holdings'][0]['asset']['assetClass'],
            region: asset.region as PortfolioDefinition['holdings'][0]['asset']['region'],
            currency: asset.currency,
            provider: asset.provider,
            expenseRatio: asset.expenseRatio,
            inceptionDate: asset.inceptionDate,
          },
          targetWeight: h.weight,
        };
      })
      .filter((h): h is NonNullable<typeof h> => h !== null),
    tags: [t.category.toLowerCase(), t.riskLevel],
  }));
}

export function getTemplateMetadata(): (TemplateEntry & { holdingCount: number })[] {
  return RAW_TEMPLATES.map((t) => ({
    ...t,
    holdingCount: t.holdings.length,
  }));
}

export type { TemplateEntry };
